/**
 * Mock Data Factory Template
 *
 * Generated by test-infrastructure skill
 *
 * This template provides type-safe factory functions for generating test data
 * using @faker-js/faker, with builder pattern for complex scenarios.
 *
 * INSTRUCTIONS:
 * - Replace 'Entity' with your actual entity name (e.g., Asset, User, Workflow)
 * - Replace 'entity' with the camelCase version
 * - Update the import statements with your actual types
 * - Add fields matching your TypeScript type definition
 * - Use in tests for consistent, type-safe mock data
 */

// import { faker } from '@faker-js/faker';
// import type { SupabaseClient } from '@supabase/supabase-js';
// import type { Database } from '@/types/supabase';
// import type { Entity } from '@/types/entity';

/**
 * Default mock IDs for relationships
 * Note: Define these in your factory methods as needed
 */

/**
 * Simple factory function - Replace Entity with your entity name
 * Creates a mock entity with sensible defaults
 */
export function createMockEntity(
  // overrides?: Partial<Entity>
  // ): Entity {
  overrides?: Record<string, unknown>
): Record<string, unknown> {
  return {
    // Add your fields here
    // Primary key
    // id: faker.string.nanoid(21),
    // tenant_id: DEFAULT_TENANT_ID,
    // created_by: DEFAULT_USER_ID,
    // name: faker.commerce.productName(),
    // status: 'active',
    // created_at: faker.date.recent().toISOString(),
    // updated_at: faker.date.recent().toISOString(),

    ...overrides,
  };
}

/**
 * Builder pattern for complex scenarios
 * Provides fluent API for constructing entity instances
 */
export class EntityBuilder {
  // private entity: Partial<Entity> = {};
  private entity: Record<string, unknown> = {};

  public withId(id: string): this {
    this.entity.id = id;
    return this;
  }

  public withTenant(tenantId: string): this {
    this.entity.tenant_id = tenantId;
    return this;
  }

  public build(): Record<string, unknown> {
    return createMockEntity(this.entity);
  }
}

/**
 * Batch factory - Create multiple instances at once
 */
export function createMockEntityList(
  count: number,
  overrides?: Record<string, unknown> | ((index: number) => Record<string, unknown>)
): Record<string, unknown>[] {
  return Array.from({ length: count }, (_, index) => {
    const entityOverrides = typeof overrides === 'function'
      ? overrides(index)
      : overrides;

    return createMockEntity(entityOverrides);
  });
}
