/**
 * Playwright E2E Test Template
 *
 * Generated by test-infrastructure skill
 *
 * This template provides a complete E2E test structure using Playwright,
 * with Page Object Model pattern, auth setup, and common utilities.
 *
 * INSTRUCTIONS:
 * - Replace 'Feature' and 'feature' with your actual feature name
 * - Customize selectors for your application
 * - Add test cases based on user flows
 */

import { test, expect, type Page } from '@playwright/test';

/**
 * Page Object Model: FeaturePage
 *
 * Encapsulates all selectors and actions for the feature
 */
class FeaturePage {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  // Selectors
  readonly selectors = {
    // Navigation
    navBar: '[data-testid="nav-bar"]',
    userMenu: '[data-testid="user-menu"]',
    logoutButton: 'button:has-text("Logout")',

    // Feature-specific selectors
    mainContainer: '[data-testid="feature-container"]',
    title: '[data-testid="feature-title"]',

    // Form elements (if applicable)
    form: 'form[data-testid="feature-form"]',
    submitButton: 'button[type="submit"]',
    cancelButton: 'button:has-text("Cancel")',

    // Data display
    dataGrid: '[data-testid="feature-grid"]',
    dataRow: '[data-testid="feature-row"]',
    emptyState: '[data-testid="empty-state"]',

    // Status/feedback
    successMessage: '[data-testid="success-message"]',
    errorMessage: '[data-testid="error-message"]',
    loadingSpinner: '[data-testid="loading-spinner"]',
  };

  // Actions
  async navigate(path: string): Promise<void> {
    await this.page.goto(path);
  }

  async isVisible(selector: string): Promise<boolean> {
    return this.page.locator(selector).isVisible();
  }

  async click(selector: string): Promise<void> {
    await this.page.locator(selector).click();
  }

  async fill(selector: string, value: string): Promise<void> {
    await this.page.locator(selector).fill(value);
  }

  async getText(selector: string): Promise<string | null> {
    return this.page.locator(selector).textContent();
  }
}

/**
 * Test Suite: Feature Tests
 */
test.describe('Feature Tests', () => {
  let featurePage: FeaturePage;

  test.beforeEach(async ({ page }) => {
    featurePage = new FeaturePage(page);
    // Navigate to feature URL
    await featurePage.navigate('/app/feature');
  });

  test('should load feature page', async () => {
    // Check if main container is visible
    const isVisible = await featurePage.isVisible(featurePage.selectors.mainContainer);
    expect(isVisible).toBe(true);
  });

  test('should display correct title', async () => {
    const title = await featurePage.getText(featurePage.selectors.title);
    expect(title).toContain('Feature Title');
  });

  // Add more tests here
  // test('should perform feature action', async () => {
  //   await featurePage.click(featurePage.selectors.submitButton);
  //   const message = await featurePage.getText(featurePage.selectors.successMessage);
  //   expect(message).toContain('Success');
  // });
});
